### ISSUE TITLE
internal error with trailing tabs

### ISSUE THREAD

**Issue by aarzilli** [google/starlark-go#104]
The following script:

```
def f(n):
	if True:
		print("hello world")
		
```

Causes this error:

```
in.star:4:3: internal error: runtime error: index out of range
```

note that the last line contains two tab characters.

**Comment by aarzilli** [comment]
Weird, it does happen for me at that commit. Try TestFileParseTrees in https://github.com/aarzilli/starlark-go/tree/brokensyntax. Diff: https://github.com/aarzilli/starlark-go/commit/87e195c722fff5143c4641024d6b3310e260603b

**Comment by alandonovan** [comment]
Thanks, got it. When you said "that last line contains two tabs", I thought you meant the line of print, not the following blank one.
