### ISSUE TITLE
wip-stargo: varargs

### ISSUE THREAD

**Issue by glycerine** [google/starlark-go#106]
I'm still seeing oddness with varargs at c9f53cb85dd3435aac46442ae92e2f1bb835f8c7

> commit c9f53cb85dd3435aac46442ae92e2f1bb835f8c7 (HEAD -> wip-stargo, origin/wip-stargo, stargo-wip)
> Author: Alan Donovan <adonovan@google.com>
> Date:   Sat Jan 5 17:37:51 2019 -0500
>
>    staranise: prototype of dynamically loaded vet checks
>
>    Change-Id: I88be67d55ffa6b33e83dff29968f8cdacfda3f64

~~~
>>> load("go", fmt="fmt")
>>> fmt.Printf("hi\n")
Traceback (most recent call last):
  <stdin>:1: in <expr>
Error: in call to fmt.Printf, got 1 arguments, want 2
>>>
~~~

Alan commented on the list:
>  Thanks, fixed now. (I'm continually rewriting the history of the wip-stargo branch, BTW).

I think c9f53cb85dd3435aac46442ae92e2f1bb835f8c7 is the latest. But with the history rewrite I can't really tell for sure. Git deletes the actual dates.

**Comment by alandonovan** [comment]
That's strange, I can't reproduce it at that commit, even with a go clean thrown in.

```
$ git co c9f53cb 
HEAD is now at c9f53cb staranise: prototype of dynamically loaded vet checks
$ go clean
$ go build -o stargo.exe  ./stargo/cmd/stargo/
$ ./stargo.exe 
>>> load("go", fmt="fmt")
>>> fmt.Printf("hi\n")
hi
(3, None)
>>> ^D
$ go version
go version devel +af21ffd86a Mon Nov 19 15:20:54 2018 +0000 linux/amd64
```

If you don't get identical results, it's conceivably due to a toolchain difference, but that's very unlikely since stargo depends on 1.12, so your go version and mine can't be far apart.

**Comment by glycerine** [comment]
My mistake. I did `go install` at the toplevel but that didn't give me a new `stargo` binary. It works.
~~~
>>> fmt.Printf("hi\n")
hi
(3, None)
>>>
~~~

**Comment by alandonovan** [comment]
I can never remember what go install does or where it puts its output.
