### ISSUE TITLE
Mismatch with Python: reversed(x) is subscriptable

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#127]
Both Python2 and Python3 reject `reversed([1, 2])[0]` and `reversed([1, 2])[0] = 6`. starlark accepts both. This is an immediate consequence of the spec:

> `reversed(x)` returns a new list [...]

I don't really think we want to change the starlark behavior, but since it does disagree with both Pythons, I did want to call it out for an explicit decision.

**Comment by alandonovan** [comment]
I wonder what is the point of the Python approach. If the x is indexable it's trivial to make reversed(x) indexable, whether as a copy or a read-through view.  If x is not indexable, you have to slurp up all the elements into a new list and then reverse it, which is then trivially indexable as a copy. Either way, the result is naturally indexable; the only question is whether it should be a view (ro or rw) or a copy; since a copy is the only semantics implementable for all values of x, it seems like the sensible choice.

**Comment by josharian** [comment]
IANABDFL, but I think it is as a performance optimization.

Observe:

```
$ time python3 -c "print(next(reversed(range(1))))"
0

real	0m0.043s
user	0m0.030s
sys	0m0.009s
$ time python3 -c "print(next(reversed(range(1000))))"
999

real	0m0.051s
user	0m0.032s
sys	0m0.012s
$ time python3 -c "print(next(reversed(range(1000000))))"
999999

real	0m0.043s
user	0m0.030s
sys	0m0.009s
$ time python3 -c "print(next(reversed(range(1000000000))))"
999999999

real	0m0.043s
user	0m0.029s
sys	0m0.009s
$ time starlark -c "print(reversed(range(1))[0])"
0

real	0m0.007s
user	0m0.003s
sys	0m0.003s
$ time starlark -c "print(reversed(range(1000))[0])"
999

real	0m0.008s
user	0m0.003s
sys	0m0.003s
$ time starlark -c "print(reversed(range(1000000))[0])"
999999

real	0m0.128s
user	0m0.126s
sys	0m0.017s
$ time starlark -c "print(reversed(range(1000000000))[0])"
^C

real	0m59.221s
user	1m27.468s
sys	1m12.519s
```

> If x is not indexable, you have to slurp up all the elements into a new list and then reverse it, which is then trivially indexable as a copy.

Not necessarily. Consider built-ins (like range) or classes with the `__reversed__` magic method: https://docs.python.org/3/reference/datamodel.html#object.__reversed__

**Comment by alandonovan** [comment]
I see. So __reversed__ is for types that are not indexable yet can be trivially reversed, such as a tree.

I suppose Starlark could (re-)define reversed to return an iterable, and the Go implementation could define a ReverseIterable interface to match __reversed__, but there seems little need.

**Comment by josharian** [comment]
> there seems little need.

Agreed. The only question as I see it is whether we want to do any future proofing by outlawing indexing now before starlark usage explodes (as it obviously is going to do).

I also think it’d be perfectly reasonable to decide to keep it as it is forever.

**Comment by alandonovan** [comment]
> before starlark usage explodes (as it obviously is going to do).

:)

Seems like a question for the the spec guardians at bazelbuild.

**Comment by josharian** [comment]
Right. I should have started there. Closing this in favor of https://github.com/bazelbuild/starlark/issues/29
