### ISSUE TITLE
reject dict(None)

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#128]
```
$ python2 -c 'print(dict(None))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object is not iterable
(exit 1)

$ python3 -c 'print(dict(None))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object is not iterable
(exit 1)

$ starlark -c 'print(dict(None))'
{}
(exit 0)
```

The spec says:

> dict creates a dictionary. It accepts up to one positional argument, which is interpreted as an iterable of two-element sequences (pairs), each specifying a key/value pair in the resulting dictionary.

None is not iterable, so dict should reject it.

To confirm:

```
$ starlark -c "reversed(None)"
Traceback (most recent call last):
  cmdline:1: in <toplevel>
Error: reversed: for parameter 1: got NoneType, want iterable
```

**Comment by alandonovan** [comment]
Thanks. This seems like an obvious error, and Python2, 3 and Starlark-in-Java agree. I wonder why I went to the trouble of adding 'case NoneType' in updateDict?

Fix pending.
