### ISSUE TITLE
repr(1.0) should be "1.0", not "1"

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#130]
Python chooses to always add a decimal point when using `str`/`repr` on floats:

```
$ python2 -c 'print(repr(1.0))'
1.0
(exit 0)

$ python3 -c 'print(repr(1.0))'
1.0
(exit 0)

$ starlark-go -float -c 'print(repr(1.0))'
1
(exit 0)
```

In case you're curious, go-fuzz found this because Python and starlark disagree about whether `int(repr(1.0))` is valid:

```
$ python2 -c 'int(repr(1.0))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '1.0'
(exit 1)

$ python3 -c 'int(repr(1.0))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '1.0'
(exit 1)

$ starlark-go -float -c 'int(repr(1.0))'

(exit 0)
```

Though there's nothing in the spec that says that the decimal point must be present for floats, it's probably preferable from a debugging perspective.

Status: needs decision

**Comment by alandonovan** [comment]
The spec now mandates that repr(1.0) == "1.0", and the Go implementation does that.
