### ISSUE TITLE
should not be able to assign to predeclared identifiers

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#133]
```
$ python2 -c 'None=0'
  File "<string>", line 1
SyntaxError: cannot assign to None
(exit 1)

$ python3 -c 'None=0'
  File "<string>", line 1
SyntaxError: can't assign to keyword
(exit 1)

$ starlark-go -c 'None=0'

(exit 0)
```

starlark should reject `None=0`.

The spec agrees (see final sentence):

> At the root of the tree is the predeclared block, which binds several names implicitly. The set of predeclared names includes the universal constant values None, True, and False, and various built-in functions such as len and list; these functions are immutable and stateless. An application may pre-declare additional names to provide domain-specific functions to that file, for example. These additional functions may have side effects on the application. Starlark programs cannot change the set of predeclared bindings or assign new values to them.

**Comment by alandonovan** [comment]
The sentence agrees with the implementation: when you say None=1, you're defining a global called None that shadows the predeclared name. The predeclared None is still there, and you can't change it.

This is a crucial feature for language evolvability; without it, every time we add a new predeclared name to the language, we would break every file that uses it as a global.

The reason Python rejects these examples is that treats None, False and True as keywords, not identifiers; try again with len and you'll see a different result. Perhaps Starlark should do the same, but that's a slightly different request. To me it seems like more spec complexity to outlaw idiocy.

**Comment by josharian** [comment]
Ah, I see. I misread the spec.

I agree, predeclared identifiers are preferable to keywords, and it's not worth attempting to outlaw idiocy. Thanks.
