### ISSUE TITLE
Add support for keyword-only arguments

### ISSUE THREAD

**Issue by gpshead** [google/starlark-go#15]
Because unnamed arguments on BUILD rules are never a good idea for BUILD code health but are difficult for rule authors to disallow without jumping through hoops today.

A rule definition should be able to look like this:

```python
def rule_name(*, name, parameter, optional_thing=None):
  if optional_thing is None:
    optional_thing = {}
  ...
```

Instead of the unnatural workaround that nobody seems to realize they need to write of:

```python
def rule_name(**kwargs):
  name = kwargs.pop('name')
  parameter = kwargs.pop('parameter', [])
  optional_thing = kwargs.pop('optional_thing', {})
  if kwargs:
    # Manually fail with an error message about unknown arguments.
  ...
```

b/70686810 internally.

**Comment by alandonovan** [comment]
This feature was implemented in Starlark-in-Java but is being withdrawn to keep Python2 syntax compatibility; see https://github.com/bazelbuild/starlark/issues/13#issuecomment-446005938.
I wrote a Go implementation https://github.com/google/starlark-go/pull/62 then reverted it.

If we want to add it back, the place to request it is at bazelbuild/starlark.  Relevant: https://github.com/bazelbuild/starlark/issues/27
