### ISSUE TITLE
The benchmark called "Benchmark" fails when executed because nested defs aren't enabled.

### ISSUE THREAD

**Issue by mknyszek** [google/starlark-go#152]
I tried running the benchmark "Benchmark" via the following commands:

```
$ go get go.starlark.net/starlark
$ go test -bench="Benchmark$" go.starlark.net/starlark
```

and got the following output

```
--- FAIL: Benchmark
    eval_test.go:445: /home/mknyszek/go/src/go.starlark.net/starlark/testdata/benchmark.star:9:3: this Starlark dialect does not support nested def
FAIL
exit status 1
FAIL    go.starlark.net/starlark        0.185s
```

Perhaps I missed a flag or something somewhere, so I apologize in advance for the noise if so.

On a side note, I'm personally interested in seeing some end-to-end benchmarks of more complex and realistic Starlark scripts. :)

**Comment by adonovan** [comment]
Thanks, I've mailed #153 to fix this.

> On a side note, I'm personally interested in seeing some end-to-end benchmarks of more complex and realistic Starlark scripts. :)

Well, "be the change you wish to see in the world". ;-)  

I have my own benchmarks of Starlark-Go but they're embedded in a large application that unfortunately I can't share.  In a single thread it's slower than CPython, but if you have many Starlark threads and a multiprocessor, it scales much better.

**Comment by mknyszek** [comment]
> Well, "be the change you wish to see in the world". ;-)
Fair enough. :)

Thank you for the quick fix!
