### ISSUE TITLE
Bare '*' in def(*, a=1, ...) breaks expectation that UnaryExpr always has a subnode 

### ISSUE THREAD

**Issue by vadimsht** [google/starlark-go#157]
This caused at least two bugs:

### syntax.Walk is aborted midway

syntax.Walk stopped working due to recursing into nil node here: 
https://github.com/google/starlark-go/blob/4eb76950c5f02ec5bcfd3ca898231a6543942fd9/syntax/walk.go#L125

What's funny is that it then panics with `panic(n)` where `n` is nil:
https://github.com/google/starlark-go/blob/4eb76950c5f02ec5bcfd3ca898231a6543942fd9/syntax/walk.go#L148

And this panic doesn't result in any observable error: `recover()` returns nil as if nothing has happened :) 

I noticed this bug because comments attached to a DefStmt node mysteriously disappear if a function has '*' in params list (`assignComments` is silently panicing midway through its execution).

### Panic in UnaryExpr.Span

After adding `if n.X != nil {...}` check, the next failure is nil dereferencing in UnaryExpr.Span with the following stack trace (line numbers are for commit 4eb7695):

```
  	.../runtime/panic.go:513 +0x1b9
  go.starlark.net/syntax.(*UnaryExpr).Span(0xc000074600, 0xc0000525d0, 0x500000013, 0xc0000525d0, 0xa00000013)
  	.../go.starlark.net/syntax/syntax.go:491 +0x2a
  go.starlark.net/syntax.(*parser).assignComments(0xc00005e3c0, 0x121c540, 0xc00005e4e0)
  	.../go.starlark.net/syntax/parse.go:1010 +0x5dc
  go.starlark.net/syntax.Parse(0x11eca44, 0x8, 0x11a5f00, 0xc0000525c0, 0x1, 0x1183d77, 0x10d6c8f, 0x1183d76)
  	.../go.starlark.net/syntax/parse.go:46 +0x132
```

(Btw getting this helpful stack trace required commenting out recover() in `Parse`. Please consider not recovering if debug == true).

-----

At this point I gave up since it seems it might be cleaner to introduce a new AST node kind rather than try to catch all places where UnaryExpr is assumed to have a subnode. Thus just reporting my findings here for you to pick the best approach. 

If you have a preferred fix in mind (e.g. hunt down all places that use UnaryExpr.X and make sure they accept nil, or introduce a new StarExpr, or something else), but don't have time to implement it soonish, please let me know and I'll try to write a CL (since I'm semi-blocked on this bug now).

Thanks!

**Comment by alandonovan** [comment]
Thanks for the detailed report. I've sent a fix. I'd prefer to keep representing * and *args using UnaryExpr{Op:STAR} to avoid multiplying syntax types unnecessarily. We already have an analogous special case of *param=default, which is represented using BinaryExpr.
