### ISSUE TITLE
Errors parsing "def f(*args, a, c,): ..." (with trailing comma in args list)

### ISSUE THREAD

**Issue by vadimsht** [google/starlark-go#159]
Trailing comma after the last argument in the function definition causes parsing errors if args have '*' or '*args':

```
>>> def f1(a, b, c,): pass  # works
...
>>> def f2(*, a, b, c): pass  # works
...
>>> def f3(*, a, b, c,): pass  # doesn't :(
<stdin>:1:20: got ')', want parameter
>>> def f4(a=None,): pass  # works
...
>>> def f5(*args, a=None,): pass  # doesn't :(
<stdin>:1:23: got ')', want parameter
```

This is most important for functions with huge arguments list, since it's pretty common to end the last argument with a comma, e.g.

```
def func(
    *,
    arg1=None,
    arg2=None,
    arg3=None,
    ...
    argN=None,
  ):
  ...
```

(I believe the spec allows it).

**Comment by josharian** [comment]
Duplicate of #83?

**Comment by vadimsht** [comment]
Hm, I think you are correct. python2 also refuses to parse `def f5(*args, a=None,): pass`.
