### ISSUE TITLE
starlark: profiler records incorrect Profile.time (Jan 1 1970)

### ISSUE THREAD

**Issue by alandonovan** [google/starlark-go#186]
Most likely a consequence of using the MONOTONIC not REALTIME clock.

**Comment by josharian** [comment]
I haven't had a chance to fully grok through the original PR or the subsequent one, but I did see a comment along the lines of "CLOCK_GETTIME is not available". But I believe it should be, in golang.org/x/sys. I added it recently for darwin (https://github.com/golang/sys/commit/3b5209105503162ded1863c307ac66fec31120dd) and it was there already for linux.

Please ignore this comment if it is unhelpful. :)

**Comment by alandonovan** [comment]
Thanks. I've noted this in the comment.
