### ISSUE TITLE
Time and Duration support?

### ISSUE THREAD

**Issue by natefinch** [google/starlark-go#19]
I know bazel's skylark eschews time functions because they want to ensure reproducibility in their configurations, but this implementation of skylark seems like it could be used for so much more, and at least having access to official skylark time and duration types would keep implementations compatible that otherwise would not be, if consumers all create their own implementations.

Even purely from a configuration standpoint, I could definitely see wanting to be able to specify durations for timeouts, or timestamps for expiration dates, etc.

**Comment by srebhan** [comment]
@alandonovan this should be solved by the recently added time support.

**Comment by srebhan** [comment]
@adonovan this issue can be closed as https://github.com/google/starlark-go/tree/master/lib/time exists now.

**Comment by adonovan** [comment]
Indeed it can. Many thanks for this contribution!
