### ISSUE TITLE
starlark: reject duplicate keyword arguments in function call even when callee has **kwargs

### ISSUE THREAD

**Issue by alandonovan** [google/starlark-go#21]
```
$ cat a.star
def f(*args, **kwargs):
        print(args, kwargs)

f(x=1, y=2)
f(x=1, x=2)

$ starlark a.star
() {"x": 1, "y": 2}
() {"x": 2} # should be an error
```

Python2, Python3 and Starlark-in-Java all reject repetition of a keyword argument in a function call. Starlark-in-Go should to.  (It does when the callee is a regular function but not when it has a **kwargs parameter.)

**Comment by laurentlb** [comment]
Note that you'll need a runtime check, in case there's a `**kwargs`.

**Comment by oprypin** [comment]
Should the same apply to Go-implemented callables? I'm getting duplicate kwargs in them.

```go
func (zzz) CallInternal(thread *starlark.Thread, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	fmt.Fprintln(os.Stderr, kwargs)
```

```python
zzz(arg = "value1", arg = "value2")
```

```
[("arg", "value1") ("arg", "value2")]
```

Maybe it's not the nicest (in terms of code) to prevent this, but otherwise every implementation of a callable would have to be wary of this.

**Comment by oprypin** [comment]
Hm, maybe it's some kind of bug, because when I try to show a problem on a minimal test case, it fails "correctly"

And there's certainly code to handle this

https://github.com/google/starlark-go/blob/6ddc71c0ba77217b518c586dc8589d627c92ebfb/resolve/resolve.go#L735-L736

I'll look into this more

**Comment by oprypin** [comment]
Ah right, here's an actual repro

```python
zzz(
    foo = "a",
    **{"foo": "b"}
)
```
```
[("foo", "a") ("foo", "b")]
```

**Comment by alandonovan** [comment]
The calling convention says a callee gets a list of positional arguments and a list of named arguments. It's up to the callee what they do with them. Starlark functions, and builtins that use UnpackArgs to interpret parameters, both reject duplicates, but one could imagine a built-in that put them to good (albeit possibly surprising) use.
