### ISSUE TITLE
Doc bug (?): UnpackArgs's optional params must all be marked with "?".

### ISSUE THREAD

**Issue by viettrungluu** [google/starlark-go#212]
I think this is a documentation bug, but it might also be an implementation bug. For `UnpackArgs`, it says:
```
// If the parameter name ends with "?",
// it and all following parameters are optional.
```
To me, this implies that you only need to mark the first optional parameter with "?" and all following parameters are automatically optional.

However, the check is:
```
        // Check that all non-optional parameters are defined.
        // (We needn't check the first len(args).)
        for i := len(args); i < nparams; i++ {
```
In skipping the first `len(args)`, you might skip over the first one marked with "?".

So the requirement (with the current implementation) seems to be that all optional parameters must be marked with "?" (and that they must be consecutive at the end of the list).

(Or you could make it work as the comment suggests by not skipping the first `len(args)`.)

**Comment by alandonovan** [comment]
@nicks Nick, perhaps you could fold this into your PR?

**Comment by nicks** [comment]
:+1: sure!

**Comment by nicks** [comment]
re-reading this code, I think the bug report is wrong, because it misses the "break" a few lines below. I'm folding a test for it under https://github.com/google/starlark-go/pull/350
