### ISSUE TITLE
How to read/write json data using starlark?

### ISSUE THREAD

**Issue by tamalsaha** [google/starlark-go#215]
Is there any example that shows how to read write json data using starlark ?

**Comment by alandonovan** [comment]
We don't yet have a module for JSON access, though there is clearly a need. I posted a first draft in https://github.com/google/starlark-go/pull/179 but have not had time to finish it off. I hope to return to it in the near future, in combination with support for reading and writing protocol messages. I think the combination will open many doors for new tooling.

**Comment by tamalsaha** [comment]
I would like to see the `json` support being added. This will make it an interesting embedded scripting language in the Kubernetes context where all api responses are json. Looking forward to this.

**Comment by errordeveloper** [comment]
I'd like to build a complex object (like a Kubernetes resource) in a starlark script and return it back to my Go program as a JSON script or something that can be easily parsed in the same manager as JSON.

**Comment by tamalsaha** [comment]
@errordeveloper , for Kubernetes YAML, the better option will the kyaml library which preserves the comments, yaml order etc. There are some examples here:
https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/starlark/example_test.go

**Comment by errordeveloper** [comment]
@tamalsaha interesting, didn't expect that kustomize would add starlark in, I was previously told it would be against the original design... Will have a good look, thanks! For now I am actually quite keen to try out CUE for the use-case at hand.

**Comment by dilyevsky** [comment]
@tamalsaha maybe https://github.com/cruise-automation/isopod would be of interest. It uses implementation in skycfg (https://github.com/stripe/skycfg/blob/2a2d2baed02b9ef17e98fdbdd1d7255e9adfbad3/internal/go/skycfg/json_write.go#L45) to render json for CRD types (but normally uses Protobuf wire format where supported)

**Comment by alandonovan** [comment]
PR #179 is committed, so you can start to use json.encode and json.decode within your Starlark application. Of course Starlark programs still cannot read or write files unless the application provides a way to do that.

I may move the Go code into a lib/json directory, which is a breaking API change but not a breaking Starlark language change.

Please try it out and report any problems.
