### ISSUE TITLE
doc: example of exposing a Go function to a Starlark program

### ISSUE THREAD

**Issue by tamalsaha** [google/starlark-go#216]
Is it possible to expose GO functions as runtime methods into starlark program?

**Comment by alandonovan** [comment]
Of course! See https://github.com/google/starlark-go/blob/master/starlarktest/starlarktest.go#L62  for an example in which several functions are predeclared in the environment before calling ExecFile. See https://github.com/google/starlark-go/blob/master/starlarktest/starlarktest.go#L90 for the implementation of one of those functions, `matches`.

I should probably add an example to starlark/example_test.go; currently it shows how to add a new type but not a standalone function.
