### ISSUE TITLE
Who uses this Go implementation?

### ISSUE THREAD

**Issue by tamalsaha** [google/starlark-go#219]
From readme file, I get the impression that the Java version is used in Bazel. Is this  Go implementation used by any project? How complete and well-tested is this implementation?

**Comment by alandonovan** [comment]
It's used by a number of projects internal to Google, by Stripe, by Kubernetes, by qri.io, and as of today, by the Delve debugger for Go. A few other open-source clients are listed here: https://godoc.org/go.starlark.net/starlark?importers

The Go implementation is complete according to the spec, more cleanly implemented, and much more efficient than the Java implementation, though I am currently trying to improve the latter. Also, Google Summer of Code is currently sponsoring an engineer to identify, report, and fix discrepancies between the implementations.
