### ISSUE TITLE
standardization: syntax used to describe types as string in `type`

### ISSUE THREAD

**Issue by mcuadros** [google/starlark-go#225]
I wonder what kind of syntax should be used to describe complex custom types. 
Should be used the python format, like `<class 'Foo'>`?

**Comment by alandonovan** [comment]
For the Value.type() method, just return "Foo". Bazel uses "Rule", "Aspect", and "select", for example. Avoid names used by core built-in types, like "list". It is a little unsatisfactory that Starlark uses strings and not distinguished objects as type symbols, but it has yet to be a problem in practice.

**Comment by mcuadros** [comment]
I am speaking about custom types, so for a custom type implementing `starlark.Value` what kind of format should be used to return the type in the `starlark.Value.Type() string` function. To describe the instance of this type, with a more descriptive name than just the name of the type. 

As you can see in Python, they return the name of the Class and not just "Class"

**Comment by alandonovan** [comment]
For most implementations of starlark.Value, the type string corresponds exactly to the Go type name: List.type returns "list".

As a more complex example, Google has an internal Starlark package for handing protocol messages, and it produces type strings such as "proto.Message<foo.Bar>" where proto.Message is fixed, and foo.Bar, the name of the protocol message type, varies. If a Value implementation defines the CompareSameType method, the method is called only when comparing two values of the same type string, so proto.Message<A> and proto.Message<B> are incomparable.

So I guess the implied invariant here is: within an application, values of different Go types must produce different Starlark type strings. But two values of the same Go type may have the same type string (e.g. two lists) or different strings (e.g. proto.Message<A> and proto.Message<B>).

**Comment by alandonovan** [comment]
(See latest draft of previous note for valid markdown.)
