### ISSUE TITLE
Mailing list is inaccessible

### ISSUE THREAD

**Issue by shields-fn** [google/starlark-go#239]
`README.md` points to https://groups.google.com/forum/#!forum/starlark-go, but this gives the error: `You do not have permission to access this content. (#418)`

**Comment by AlekSi** [comment]
![image](https://user-images.githubusercontent.com/11512/86327009-353d4b80-bc4b-11ea-9a8b-dd5c23910c15.png)

@adonovan Does this group exist?

**Comment by alandonovan** [comment]
Sorry about that. Try again now.
