### ISSUE TITLE
allow load to accept non-literal strings

### ISSUE THREAD

**Issue by cppforlife** [google/starlark-go#246]
one of the users of ytt [1] reported that they couldn't use string variable as a first arg to load statement: https://github.com/k14s/ytt/issues/59. i was a bit surprised and double checked that that's actually the case: https://gist.github.com/cppforlife/3f10ce311ea7a71c55936cc50abe2244, and indeed it is.

im curious why this restriction was put in place vs allowing load statement accept string arg, in any way it's constructed.

related code: https://github.com/google/starlark-go/blob/6ddc71c0ba77217b518c586dc8589d627c92ebfb/syntax/parse.go#L320-L322

on an unrelated note, i would like to thank you all for this great project. it has been a pleasure working with its APIs. 

[1] https://get-ytt.io (ytt is a YAML templating tool; we use starlark-go as our templating language)

**Comment by alandonovan** [comment]
This restriction is normal in compiled languages, and even Python's `import` statement imposes a similar restriction. (Yes, Python does have the __import__ function, but few programs need it, and it definitely falls into the category of too-clever features that are ripe for abuse.)

Being able to understand the structure of a program without executing it is an important property for program comprehension, both for programmers and for tools. For example, an IDE can connect references to definitions if it can know statically what module is being loaded, but it would have no hope if the module whose name was computed.

Glad you've been finding it useful!
