### ISSUE TITLE
evaluator incorrectly allows f(*args, k=v)

### ISSUE THREAD

**Issue by alandonovan** [google/starlark-go#271]
The spec says arguments must conform to the order positionals < keywords < *args < **kwargs, but the implementation in fact implements the weaker order required by Python2: positionals < {keywords,*args} < **kwargs. For example:

```
$ starlark
Welcome to Starlark (go.starlark.net)
>>> def f(x): print(x); return x
>>> def g(*args, **kwargs): return (args, kwargs)
>>> g(f(1), k=f(2), *[f(3)], k2=f(4), **dict(k3=f(5)))
1
2
4
3
5
((1, 3), {"k": 2, "k2": 4, "k3": 5})
>>>  
```

The reason the spec requires the stricter order is that it is easy to compile while ensuring that side effects occur in left-to-right source order. The Go implementation should reject keyword arguments following a *args argument. The Java implementation already does so.

Also, the spec wording could be improved on argument passing and the rationale for the strict order.

See https://github.com/bazelbuild/starlark/issues/13 for original discussion leading to current spec, and https://github.com/google/starlark-go/blob/master/internal/compile/compile.go#L1677 for discussion of rejected alternatives.

**Comment by SamWheating** [comment]
I believe this was fixed in https://github.com/google/starlark-go/pull/317
