### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by arctica** [google/starlark-go#273]
Hi, I came across the project while looking for a scripting language that can be embedded into a Go program.

My main use case would be data analysis and the scripts might be ingesting and processing many millions of datapoints so performance shouldn't be too bad.

Are there any benchmarks that compare starlark-go to other Go embeddable scripting languages like tengo, goja, anko etc?

PS: I really appreciate the first impression of the project with its pretty comprehensive documentation.

**Comment by alandonovan** [comment]
No, I don't have any benchmarks of that sort, though if you do prepare some during your research I would be happy to review them and to publish the results here.

My goal for this project has been to achieve the best performance possible for an interpreted Python-like language in Go without going past the knee of the complexity curve. That is, the asymptotic performance of each operation is what you would expect, and makes the minimum number of memory allocations, but I haven't attempted heroic measures like trace-based dynamic compilation, for example.

The biggest weakness is likely integer performance, which doesn't matter at all in a build system.

Thanks for the kind words!

**Comment by alandonovan** [comment]
I suggest you talk to @b5 Brendan O'Brien at qri.io, as they use Starlark as a query language for "big data" sets.

Integer performance has improved since my last comment.

Closing this for now.
