### ISSUE TITLE
scanner should allow \" within both '...' and "..." quotations

### ISSUE THREAD

**Issue by nicks** [google/starlark-go#278]
Repro steps:

test.sky
```
x = '\"'
```

Run it with:

```
$ starlark test.sky
../test.sky:1:5: invalid escape sequence \"
```

I understand the argument why this *shouldn't* be a valid string escape, per
https://github.com/google/starlark-go/pull/265

but this seems inconsistent with Python 3.8, which treats this as valid, and doesn't emit any warnings:
python3 -Wall test.sky

**Comment by laurentlb** [comment]
The Java implementation explicitly supports it:
https://cs.opensource.google/bazel/bazel/+/034b09e810de42baac8e1a431eab6acd91b2c8a1:src/main/java/com/google/devtools/build/lib/syntax/Lexer.java;l=315,318

The Python 3 documentation mentions a deprecation for the unrecognized escape sequences (like Starlark). But the documentation explicitly lists `\"` and `\'` as valid:
https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

Even if it's surprising to have those useless escapes, I think starlark-go should allow them.

**Comment by alandonovan** [comment]
Yes, as you point out this is inconsistent with Python 3.8---though presumably Python 3.9 or later will catch up. This was the explicit intent of #265: 

https://github.com/google/starlark-go/pull/265/files#diff-fe578779dc15d59765499b7151c7c926R123:
```
// In Starlark, like Go, a backslash must escape something.
// then it appears as literal text in the string.
// (Python still treats unnecessary backslashes literally,
// but since 3.6 has emitted a deprecation warning.)
```

https://github.com/google/starlark-go/pull/265/files#diff-a37bdfbd0d2f3627958003f87033871eR449:
```
It is an error for a backslash to appear within a string literal other
than as part of one of the escapes described above.
```

The motivation for strict escapes is that you can never add a new interpretation for say `\k` if we already permit `\k` to appear in strings. This is the reason Python is trying to eliminate this feature.

@laurentlb why do you think starlark-go should add back this feature of which Python is trying to rid itself? Reading starlark-java, it appears to be moving in the same direction:
https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/syntax/FileOptions.java#L48

**Comment by laurentlb** [comment]
The bug is specifically about backslash+quote (I think we all agree that `\k` should be rejected).

Here's Python behavior:

```
$ python -Wall
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> "\k"
<stdin>:1: DeprecationWarning: invalid escape sequence \k
'\\k'
>>> "\'"
"'"
```

This is consistent with [Python documentation](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) which has a table with the list of supported escape sequences:

```
Escape Sequence | Meaning | Notes

\newline | Backslash and newline ignored |  
\\ | Backslash (\) |  
\' | Single quote (') |  
\" | Double quote (")
...
```

According to the documentation, the escape sequence `\'` is always valid, whether the string is surrounded by single quotes (in which case the escape is required) or double quotes (in which case the escape is useless). Python 3 and Starlark-Java agree on this.

**Comment by alandonovan** [comment]
Got it---sorry for my misunderstanding. I'll add \' and \" to the list of escapes.

**Comment by nicks** [comment]
thanks @alandonovan! ya, totally agree that \k should be rejected and glad that there's progress on this being fixed in python! :grinning:

**Comment by rockmenjack** [comment]
need to support \` as well,  as it is required in e.g. mariadb:

```sql
SELECT * FROM `temp_01-01-000001`
``` 
currently it will fail with `invalid escape sequence \``

**Comment by rockmenjack** [comment]
> need to support ` as well, as it is required in e.g. mariadb:
> 
> ```sql
> SELECT * FROM `temp_01-01-000001`
> ```
> 
> currently if i were to generate above sql and execute in a shell, i need to escape backtick by `` SELECT * FROM \`temp_01-01-000001\` ``, but it will fail with `` invalid escape sequence \` ``

seems it should be ``` \\` ```, please ignore the above
