### ISSUE TITLE
Is it possible to check if the name is defined?

### ISSUE THREAD

**Issue by AlekSi** [google/starlark-go#286]
I have a fixed starlark environment that I can't change. I run scripts there that I can change. Can starlark script check that global or local variable or constant is defined in that case? I assume not, given that `globals()`, `locals()` and `vars()` are not implemented, as well as exceptions (so I can't use `NameError`). But maybe I miss something?

**Comment by alandonovan** [comment]
No, there is no way to do this, though it would be useful for writing scripts that work in two "dialects", such as before and after the introduction or removal of a predeclared name.

Python allows `dir()` to be called with no arguments, which returns the list of names local variables, if called from with in a function, or of the globals, if called from toplevel (unless in a list comprehension, in which case it returns the globals and locals).  Starlark's dir does not support this---and given the complexity of the foregoing description, that's no bad thing.

**Comment by AlekSi** [comment]
After thinking about it more, I understood that I don't really need global constants. I will do something like that:
```
def foo(data):
    foo_v2(data, {})

def foo_v2(data, metadata):
    if metadata["foo"]:
        ...
```

The old environment will call `foo`, and the new environment will call `foo_v2` with metadata. This script can work in both environments.

Thank you.
