### ISSUE TITLE
Fatalf on darwin arm64 iOS

### ISSUE THREAD

**Issue by Dreamacro** [google/starlark-go#290]
root cause:

https://github.com/google/starlark-go/blob/50ca820fafb940caeda09b96864b9215f8b84c04/starlark/int_posix64.go#L55-L57

when targeting on darwin/arm64, it case `mmap: cannot allocate memory`

**Comment by alandonovan** [comment]
Thanks, fix in progress.

Curious: what are you using Starlark for on iOS?

**Comment by Dreamacro** [comment]
Thanks for quick fixed.

In fact, it's not an iOS-only app, it's just an attempt to port application over to iOS. It's used to write a function to handle some edge case (inject some native function helper).

BTW, mmap problem seems reproduce on rosetta2 translation program (arm macOS)

**Comment by alandonovan** [comment]
> mmap problem seems reproduce on rosetta2 translation program (arm macOS)

I had to look up Rosetta2: apparently it's an interpreter for MacOS x86 binaries that runs on (hypothetical?) new ARM-based machines running MacOS.  Obviously the Go compiler would know nothing about ARM in this case, so the build tags would select the mmap-based implementation. What's the problem? Could you be more specific?

**Comment by Dreamacro** [comment]
That was a mistake. starlark-go works fine in Rosetta2. The golang toolchain does not work on arm macOS at the moment. For now it can only be built on other device (`GOARCH=amd64 GOOS=darwin`) and sent to DTK (but not all cores can be fully used) 🌝

**Comment by Dreamacro** [comment]
Problem solved, close issue. Thanks.

**Comment by Dreamacro** [comment]
It causes `bad file descriptor` on Android (GOOS=android GOARCH=arm64) after
https://github.com/google/starlark-go/commits/474f21a9602da421b967d43fd1106f1898c70e2e

**Comment by Kr328** [comment]
commit https://github.com/google/starlark-go/commits/474f21a9602da421b967d43fd1106f1898c70e2e

cause `mmap: bad file descriptor` on Android arm64 (`GOOS=android GOARCH=arm64`) but x86 work fine (`GOOS=android GOARCH=386`)

build command
- `arm64`
```bash
CC=/path/to/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang GOOS=android GOARCH=arm64 CGO_ENABLED=1 go build
```
- `x86`
```bash
CC=/path/to/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang GOOS=android GOARCH=386 CGO_ENABLED=1 go build
```

**Comment by alandonovan** [comment]
Thanks for the fix.
