### ISSUE TITLE
Cannot cross-compile for Solaris

### ISSUE THREAD

**Issue by edigaryev** [google/starlark-go#320]
When trying to build a project that depends on starlark-go with `GOOS=solaris`, compiler throws the following error:

```
/go/pkg/mod/go.starlark.net@v0.0.0-20201014215153-dff0ae5b4820/starlark/int_posix64.go:70:12: undefined: syscall.Mmap
```

Is there a reason why `golang.org/x/sys` (which would otherwise provide the `Mmap()` implementation) was ditched in favor to a in-house implementation in https://github.com/google/starlark-go/pull/287?

**Comment by fkorotkov** [comment]
`golang.org/x/sys` is still brought via an indirect dependency through `github.com/chzyer/readline`:

```
$: go mod why -m golang.org/x/sys
# golang.org/x/sys
go.starlark.net/repl
github.com/chzyer/readline
golang.org/x/sys/unix
```

**Comment by alandonovan** [comment]
The repository does depend on sys indirectly via readline, but the interpreter itself does not depend on either package, and rolling our own system call was an attempt to avoid adding any dependencies. However, it was probably a false economy in this case.

I've mailed  https://github.com/google/starlark-go/pull/new/sys
