### ISSUE TITLE
Issue installing starlark

### ISSUE THREAD

**Issue by ARao0123** [google/starlark-go#355]
I'm trying to upgrade the version of delve to 1.60*with Go 1.16) ```
but I see an error related to starlark:

abc-MacBook-Pro:delve username$ go install github.com/go-delve/delve/cmd/dlv@latest
go install github.com/go-delve/delve/cmd/dlv@latest: github.com/go-delve/delve@none updating to
	github.com/go-delve/delve@v1.6.0 requires
	go.starlark.net@v0.0.0-20200821142938-949cc6f4b097: unrecognized import path "go.starlark.net": parse https://go.starlark.net/?go-get=1: no go-import meta tags ()
```

GOBIN = /Users/abc/go/bin
GOPATH = /Users/abc/go
GOROOT = /usr/local/go
which go = /usr/local/go/bin/go

Any idea how to fix this issue with meta-tags?

**Comment by adonovan** [comment]
I just ran this command on a mac and it succeeded. Perhaps the GitHub server behind go.starlark.net was momentarily unavailable? Could you try again and report back. Until then I'm going to assume this is transient and close it for now.
