### ISSUE TITLE
How to "pause" the evaluation (aka breakpoint)?

### ISSUE THREAD

**Issue by AlmogBaku** [google/starlark-go#408]
Hi,
I'm wondering if/how it's possible to add some mechanism for breakpoints?

I saw that there are [a](https://github.com/google/starlark-go/blob/master/starlark/interp.go#L66) [few](https://github.com/google/starlark-go/blob/master/starlark/interp.go#L116) [lines](https://github.com/google/starlark-go/blob/master/starlark/interp.go#L319) there is a "preparation" for hooking up a debugging breakpoint, but I couldn't find any way to hook there...

a. Is it possible today?
b. If that's not possible, I suggest adding a callback function in the thread or in a thread's local. If that is accepted, I'd be happy to do a PR. (The interface can be something simple like `func(thread *Thread, typ BreakpointType)`

**Comment by AlmogBaku** [comment]
PS, might be related to #304

**Comment by AlmogBaku** [comment]
@alandonovan WDYT? should I write a PR as described?

**Comment by pivotaljohn** [comment]
I think the now "proper" mention for Alan is: @adonovan.

**Comment by AlmogBaku** [comment]
@adonovan what do you think about my proposal solution?
If that's acceptable, I'd be happy to write a PR
