### ISSUE TITLE
Add support for formatted string literals (PEP 498)

### ISSUE THREAD

**Issue by raphaelfff** [google/starlark-go#416]
[PEP 498](https://www.python.org/dev/peps/pep-0498/) introduced formatted string literals which make this possible:

```
>>> name = "Star-Lord"
>>> f"Starlark, say hi to {name}"
'Starlark, say hi to Star-Lord'
```

Would be super useful for this to be present in starlark :)

**Comment by adonovan** [comment]
This is a spec change, so it doesn't belong in this repo. Closing as a dup of https://github.com/bazelbuild/starlark/issues/91.
