### ISSUE TITLE
panic from built-in function leaves Thread in a bad state

### ISSUE THREAD

**Issue by vanishs** [google/starlark-go#419]
This is the test code:
https://go.dev/play/p/SZFzWgchzeZ
```golang
package main

import (
	"fmt"
	"log"

	"go.starlark.net/starlark"
)

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

func main() {
	t := &starlark.Thread{}
	sd := starlark.StringDict{
		"test": starlark.NewBuiltin("test", func(*starlark.Thread, *starlark.Builtin, starlark.Tuple, []starlark.Tuple) (starlark.Value, error) {
			panic("panic")
			// println("123")
			return starlark.None, nil
		}),
	}
	g, err := starlark.ExecFile(t, "", `
def mytest():
	test()
`, sd)
	check(err)
	g.Freeze()
	v := g["mytest"]

	calltest := func() {
		defer func() {
			if e := recover(); e != nil {
				fmt.Println("get panic", e)
			}
		}()
		_, err = starlark.Call(t, v, make(starlark.Tuple, 0), nil)
		if err != nil {
			println("get err:", err.Error())
		}
	}

	calltest()
	calltest()

}

```

The output I am expecting is:
```
get panic panic
get panic panic
```

But the output I get is：
```
get panic panic
get err: function mytest called recursively
```

When starlark is aborted by Builtin panic, calling starlark.Call again will get an error. I would like a way to have starlark revert to a usable state without renew a Thread

**Comment by adonovan** [comment]
You need to enable the [AllowRecursion flag](https://github.com/google/starlark-go/blob/b0039bd2cfe369fe8f2bdba0614bafd1f9402dbb/cmd/starlark/starlark.go#L41) to cause the interpreter not to fail when a recursive call is encountered. (This flag also enables the use of `while` loops.)

**Comment by adonovan** [comment]
AllowRecursion is not the root problem, it's just one possible cause of panic. The fundamental issue here is that the interpreter is not designed to deal gracefully with panics in built-in functions. Perhaps it should? I've reopened the issue to track the decision.

**Comment by vanishs** [comment]
Change from
`if !resolve.AllowRecursion {`
to
`if !resolve.AllowRecursion && thread.frameAt(0).locals != nil {`

what do you think?

**Comment by vanishs** [comment]
change from
`if !resolve.AllowRecursion {`
to
`if !resolve.AllowRecursion && len(thread.stack) <= 1 {`

what do you think?

**Comment by vanishs** [comment]
change from
```golang
if frfn, ok := fr.Callable().(*Function); ok && frfn.funcode == fn.funcode {
	return nil, fmt.Errorf("function %s called recursively", fn.Name())
}
```
to
```golang
if frfn, ok := fr.Callable().(*Function); ok && frfn.funcode == fn.funcode {
	if fr.locals != nil {
		thread.stack = thread.stack[idx+1:]
		break
	}
	return nil, fmt.Errorf("function %s called recursively", fn.Name())
}
```

what do you think?

**Comment by vanishs** [comment]
After some tests, the only way is to wrap panic as an error to return the stack to correct state

in func CallInternal
change form
```golang
...
	code := f.Code

loop:
	for {
...
```
```golang
...
	code := f.Code

	defer func() {
		if e := recover(); e != nil {
			err = &EvalError{Msg: fmt.Sprint(e), cause: fmt.Errorf(fmt.Sprint(e))}
			// ITERPOP the rest of the iterator stack.
			for _, iter := range iterstack {
				iter.Done()
			}
			fr.locals = nil
		}
	}()

loop:
	for {
...
```

you can see change in here:
https://github.com/vanishs/starlark-go/commit/f5b91f58332354ea71cc8316255fe3ad6864642a

**Comment by vanishs** [comment]
Add an Explicit call:
```golang
func (thread *Thread) CallStackPop() {
	for i := len(thread.stack) - 1; i >= 0; i-- {
		fr := thread.stack[len(thread.stack)-1]
		thread.stack = thread.stack[:len(thread.stack)-1]
		if _, ok := fr.Callable().(*Function); ok {
			break
		}
	}
}
```
what do you think?

**Comment by vanishs** [comment]
> The internal invariants shouldn't be exposed. I've posted #422 containing the correct fix. The benchmark doesn't seem to show significant extra cost.

thanks! i close my pr
