### ISSUE TITLE
Mutable package-level vars are a poor choice for configuration

### ISSUE THREAD

**Issue by ash2k** [google/starlark-go#435]
Hello there! I have a project where I get this library as a transitive dependency. It's used for "stuff X". I also want to use this library for "stuff Y", unrelated to "stuff X", in the same codebase/binary. I'd like to configure the library and modules differently for different use cases. But in a few places the library uses package-level variables for "global" configuration and I cannot do what I want.

Examples:
- https://github.com/google/starlark-go/blob/acb66ad56dd25d86c91a1efc3869d4a0ec0fcbdb/lib/time/time.go#L74 
- https://github.com/google/starlark-go/blob/acb66ad56dd25d86c91a1efc3869d4a0ec0fcbdb/starlark/library.go#L34
- https://github.com/google/starlark-go/blob/acb66ad56dd25d86c91a1efc3869d4a0ec0fcbdb/resolve/resolve.go#L100-L111
- Maybe a few more places I didn't find now.

In addition to the above, global mutable variables are sometimes abused by third-party libraries. They assume they are the center of the world and mutate such variables in other packages in their `init()`. No mutable globals -> no such problems.

p.s. thank you for the library! It's great!

**Comment by ash2k** [comment]
For modules and for the "interpreter" object I'd suggest to have constructors with functional options, like what gRPC-go/etc does.

**Comment by adonovan** [comment]
It would be reasonable to construct a parallel API that used pure functions (not globals) for configuration and accepted a FileOptions struct whose zero value embodied the defaults. Each syntax.File would retain its options so that you wouldn't need to repeat it for later stages.

I've sketched it in #477. Please download the patch and try it out and let me know if it works for you.

**Comment by ash2k** [comment]
Looks good to me! I'll try it next week or so. I think it is what's needed. Thank you!

**Comment by ash2k** [comment]
I've tried the branch, it works well for my needs. The unaddressed bit is the module (or modules?) that has a global var as config. Thanks!
