### ISSUE TITLE
Expose Function defaults.

### ISSUE THREAD

**Issue by vtsao** [google/starlark-go#450]
Would it be possible to expose [Function defaults](https://sourcegraph.com/github.com/google/starlark-go@master/-/blob/starlark/value.go?L662)?

I'm working on an integration where I need to get the default values before executing the function. Exposing it may be as simple as adding a `func (fn *Function) Defaults() Tuple` function. Not sure if defaults weren't exposed on purpose?

**Comment by adonovan** [comment]
That tuple is not a valid Starlark value, as it may contain elements of type [mandatory](https://sourcegraph.com/github.com/google/starlark-go@master/-/blob/starlark/interp.go?L679-681), which are not valid values. Even if that were not the case, it seems like the representation should be encapsulated to permit future evolution.

Why do you need to access the defaults tuple? Isn't that a violation of the function abstraction?

**Comment by vtsao** [comment]
> Why do you need to access the defaults tuple?

I'm integrating Starlark functions with a command line tool we own and I want to get the types of the function parameters so I can automatically generate flags for the command. When registering flags, I need to know the type of the flag, like is it a number, list, map, etc. So I was hoping to use param defaults for that.

**Comment by adonovan** [comment]
Ok, let's add a `func (fn *Function) ParamDefault(i int) Value` method after [Param](https://sourcegraph.com/github.com/google/starlark-go@fae38c8a6d89dc410be86b76dfff475b29dba878/-/blob/starlark/value.go?L703-715), that returns nil for mandatory parameters and panics unless 0 <= i <= NumParams.

**Comment by vtsao** [comment]
Thanks, I'll create a PR.
