### ISSUE TITLE
Build failure on Go 1.16/1.17 for lib/json/json.go:238:11: v.UnsafePointer

### ISSUE THREAD

**Issue by hyorigo** [google/starlark-go#473]
Here's the error message:
```
../../../go/pkg/mod/go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca/lib/json/json.go:238:11: v.UnsafePointer undefined (type reflect.Value has no field or method UnsafePointer)
```

As per the [Go.mod](https://github.com/google/starlark-go/blob/master/go.mod) file, Go 1.16 is still in support.

This build break was introduced in: https://github.com/google/starlark-go/pull/431

https://pkg.go.dev/reflect#Value.UnsafePointer

So please fix this build break, and maybe add Go 1.16 and 1.17 in GitHub Actions CI?

**Comment by yo8** [comment]
@adonovan Please don't drop 1.16 or 1.17. Since Go 1.16 is latest version that ChatGPT and GPT-4 can understand 🥇 
My company still use 1.16 in production and some sub-system use Starlark as config language as well.

**Comment by adonovan** [comment]
If we keep 1.16 until 1.21 is released, and then declare continued support the four most recent numbered Go releases, will that suffice?
