### ISSUE TITLE
Add quit() or exit() functions

### ISSUE THREAD

**Issue by Nextraind** [google/starlark-go#478]
Just like Python itself

**Comment by adonovan** [comment]
The `quit` and `exit` functions, which are equivalent in behavior, are oddly [not documented as built-ins](https://docs.python.org/3/library/functions.html) even though in Python3 they are both regular built-ins that terminate the current thread. 

In Starlark we have the `fail` function, which similarly generates an error in the current thread. (Perhaps it should have been named exit or quit.) The REPL doesn't terminate when it encounters the error from fail; perhaps it should.

Please re-open this issue if `fail` is not suitable for your needs.

**Comment by Nextraind** [comment]
I want to quit the rest part of the script, and no throw any exceptions. `fail()` works, but it throws error.

**Comment by Nextraind** [comment]
@adonovan Btw, I can't reopen it, since I'm not a colabrator of this repo. Got no such button ---

![image](https://github.com/google/starlark-go/assets/119508779/584a223f-24c9-436a-a998-0d2e60e517f6)
