### ISSUE TITLE
unclear error on mismatched parens

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#48]
Starlark:

```
$ starlark -c "a = max(range(10))); print(a)"
cmdline:1:19: indentation error
```

Python:

```
$ python -c "a = max(range(10))); print(a)"
  File "<string>", line 1
    a = max(range(10))); print(a)
                      ^
SyntaxError: invalid syntax
```

"invalid syntax" is a lot better than "indentation error". (Even better would be "mismatched parens".)

**Comment by natefinch** [comment]
👍  I have hit this too, and should have filed a bug.  Indentation error is clearly an incorrect message.
