### ISSUE TITLE
Caching Syntax Parsing Results for Scripts Run Repeatedly

### ISSUE THREAD

**Issue by housail** [google/starlark-go#501]
**Is your feature request related to a problem? Please describe.**
I've been using Google's Go Starlark extensively for running a few of my scripts. Our team runs a set of Starlark scripts quite frequently, several times an hour. We've noticed significant computational overhead related to the repeated parsing of scripts. 

**Describe the solution you'd like**
We're looking into optimizations and one glaring point is the constant parsing of unchanging scripts. To address this, I was hoping the Starlark interpreter might support some kind of syntax parsing caching system. 

Ideally, I'd want the interpreter to parse the script once and cache the parsing result. Every time we run the same script afterward, the system should bypass the parsing step and directly use the cached parsed result unless the script changes. 

**Describe alternatives you've considered**
An alternative would be to create a separate caching mechanism in our codebase but I believe this could be a common use case that many enterprises or heavy users of Starlark might come across. 

**Additional context**
The optimisation of caching parsed scripts could significantly reduce the total execution time and computational overhead in scenarios where scripts are run repeatedly. 

Looking forward to discussing this further, any thoughts or suggestions on implementation are welcome.

Thanks!

**Comment by adonovan** [comment]
This is already supported: use [SourceProgram](https://pkg.go.dev/go.starlark.net/starlark#SourceProgram) or [FIleProgram](https://pkg.go.dev/go.starlark.net/starlark#FileProgram) to create a Program, then [Write](https://pkg.go.dev/go.starlark.net/starlark#Program.Write) to save it in compiled form, then [CompiledProgram](https://pkg.go.dev/go.starlark.net/starlark#CompiledProgram) to reload it. Compilation is a per-file operation. Make sure the same exact version of Starlark is used to read and write the compiled form; you can use the [CompilerVersion](https://pkg.go.dev/go.starlark.net/starlark#pkg-constants) constant if you need to form a sound cache key.
