### ISSUE TITLE
Passing starlark.StringDict arguments in starlark.Call

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [google/starlark-go#523]
script.star

```
def f(dict1, dict2):
    ....
```

from go, something like this

```go
// arg1 and arg2 are starlark.Dict
starlark.Call(thread, globals["f"], starlark.Tuple{arg1, arg2}, nil))
```

fails with 

```
./main.go:30:86: cannot use arg1 (variable of type starlark.Dict) 
as type starlark.Value in array or slice literal:
	starlark.Dict does not implement starlark.Value
      (Freeze method has pointer receiver)

```

Any help is appreciated. Thanks!

**Comment by adonovan** [comment]
> starlark.Dict does not implement starlark.Value  (Freeze method has pointer receiver)

The error message is trying to tell you that you need to pass the address of a string.Dict (`&d`, of type `*string.Dict`) to the Call function, because Dict itself does not satisfy the Value interface.
