### ISSUE TITLE
should not accept parenthesized stmts

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#53]
```
$ starlark -c "(print())"

$ python -c "(print())"
  File "<string>", line 1
    (print())
         ^
SyntaxError: invalid syntax
```

I'm not sure exactly where the error is here, but something is not right. :)

Found by go-fuzz, of course.

**Comment by josharian** [comment]
Haven't dug, but this might be because starlark is treating print as an expr rather than a stmt. This also showed up in go-fuzz output:

```
$ starlark -set -c "set(((),print))"
$ python -c "set(((),print))"
  File "<string>", line 1
    set(((),print))
                ^
SyntaxError: invalid syntax
```

**Comment by josharian** [comment]
The previous case is using the value of print, the built-in function. But evaluated print calls are also allowed in expression contexts:

```
$ starlark -set -c "set(((),print()))"

$ python -c "set(((),print()))"
  File "<string>", line 1
    set(((),print()))
                ^
SyntaxError: invalid syntax
```

**Comment by ttsugriy** [comment]
looks like starlark implementation matches Python3 behavior:
```
$ python3 -c "(print())"

```
But unfortunately AFAIK starlark is aiming for Python2 compatibility, so I guess the issue is legit.

**Comment by alandonovan** [comment]
"print" is just a predeclared function in Skylark, so it returns a value (None) like any other expression, and, may be parenthesized.

I would not say that Skylark aims for compatibility with Python2 more than Python3. If both Pythons do the same thing, Skylark generally does too; where they differ we have more latitude to choose which one we follow, or do something yet different.
