### ISSUE TITLE
should reject "print(S=5)"

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#54]
```
$ starlark -c "print(S=5)"
S=5
$ python -c "print(S=5)"
  File "<string>", line 1
    print(S=5)
           ^
SyntaxError: invalid syntax
```

Possibly a duplicate of #53. Found by go-fuzz.

**Comment by josharian** [comment]
Python3 handles this a bit differently:

```
$ python3 -c "print(S=5)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'S' is an invalid keyword argument for print()
```

Looks to me like this is closer to what starlark will do...and that this is effectively a duplicate of #55. I'll leave it open, though, since they'll be fixed separately, since the fix will be per-callee.

**Comment by josharian** [comment]
Actually, this spec specifies the current behavior: `Keyword arguments are preceded by their name.` Alan, do you want to keep this as-is or shift to match Python?

**Comment by alandonovan** [comment]
Neither Python nor Starlark-in-Java allow keyword arguments to print, but the bazelbuild spec (derived from the description of the Go implementation) says they are supported. I filed https://github.com/bazelbuild/starlark/issues/22 to request clarification.

**Comment by alandonovan** [comment]
Fixed by https://github.com/google/starlark-go/commit/88085a499633e675c9b29c3ff8ea2073480047a5
