### ISSUE TITLE
Is the Starlark thread thread-safe for concurrent `Exec*()`?

### ISSUE THREAD

**Issue by gpjim** [google/starlark-go#540]
I'm thinking about an extension for Starlark that requires asynchronous function calls, and I'm wondering if the Starlark thread is thread-safe, and if multiple concurrent `Exec*()` calls are possible.

Here's the prototype I'm considering:

```go
func CallFuncAsync(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwargs []starlark.Tuple) (starlark.Value, error) {
	// ...

	token := Wrapper()...
	go func() {
		fn := args[0].(*starlark.Function)
		fn.CallInternal(thread, starlark.Tuple{...}, nil)
		close(token.Chan)
	}()
	return token, nil
}
```

This function would use a goroutine to call the Starlark function in the Go runtime with the same thread, and return a token for waiting.

Is this a safe approach? If not, are there alternative ways to achieve asynchronous function calls in Starlark?

**Comment by adonovan** [comment]
No. If you need multiple threads, create multiple `Thread`s.

**Comment by adonovan** [comment]
> If I don't create a new `Thread`, it may panic for data race or something.

(Or it may not panic but silently corrupt your data.)

> But new `Thread` doesn't copy the call stack, which makes the `CallInternal` fails to find the func to call.
> 
> Here's the Go code snippet:

```go
	// call the function asynchronously
	nt := &starlark.Thread{Name: "async", Load: thread.Load, Print: thread.Print, OnMaxSteps: thread.OnMaxSteps}
	go func(thread *starlark.Thread) {
		// call the function
		val, err := fnc.CallInternal(thread, args[1:], kwargs)
		fmt.Println("[done]", val, err)
	}(nt)
```

The surface problem causing the crash is that you are calling CallInternal. You should never call it directly; use `starlark.Call`.

But there is a deeper problem, which is that you are passing unfrozen values from one thread to another. Either of the threads could mutate the value, causing another data race. You could call Freeze on all the args and kwargs passed to asyncCallFunc, but this side effect might could be very subtle and would likely be a surprise for the Starlark calling code.

In short, you are trying to do something that is not supported.

Starlark programs can be highly parallel, but the concurrency needs to be coordinated at a higher level by the host application, not by the Starlark code itself.

For example, in Bazel, each file is initialized (executed from top to bottom). If it's a .bzl file the result is a module containing a bunch of functions, which are then frozen, making them safe for concurrent execution. If it's a BUILD file, the effect is to construct part of the build dependency graph (an application data structure), which may contain some of those functions declared in the bzl file. Initialization of BUILD and bzl files, and application call-backs to bzl functions, can all be highly parallel, but there is no user-visible concurrency in any given Starlark file.
