### ISSUE TITLE
missing "keyword repeated" check for dict construction

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#55]
```
$ starlark -c "dict(S=5, S=5)"
$ python -c "dict(S=5, S=5)"
  File "<string>", line 1
SyntaxError: keyword argument repeated
```

Found by go-fuzz.

**Comment by josharian** [comment]
I have misunderstood this several times. Have to stop now, but not to future self and/or others: Normally this check is performed in `setArgs`. However, built-ins have their own `CallInternal`, which does not call `setArgs`, so built-in functions don't have duplicates of any form checked (e.g. `starlark -c "print(dict(a=1, **dict(a=1)))"`).

**Comment by alandonovan** [comment]
For efficiency, and compatibility with Python (which also does it this way for efficiency), the check belongs in the callee side: setArgs for Starlark functions, UnpackArgs for most built-ins. The few built-ins that don't use UnpackArgs (like dict) have to roll their own. I think this PR is pretty close to what is needed.

**Comment by alandonovan** [comment]
You can optimize the check away in the common case by calling updateDict first, then doing the duplicate check only if the resulting dictionary is shorter than len(kwargs).

**Comment by josharian** [comment]
Ack. Thanks, Alan.

> For efficiency, and compatibility with Python (which also does it this way for efficiency), the check belongs in the callee side

It appears that Python checks for duplicate keyword args during parsing:

```
$ python3 -c "if False: dict(S=5, S=5)"
  File "<string>", line 1
SyntaxError: keyword argument repeated
$ python2 -c "if False: dict(S=5, S=5)"
  File "<string>", line 1
SyntaxError: keyword argument repeated
```

(That is not to say that starlark should follow suit.)

**Comment by josharian** [comment]
> You can optimize the check away in the common case by calling updateDict first, then doing the duplicate check only if the resulting dictionary is shorter than len(kwargs).

Unfortunately, I don't think that that optimization is sound. Consider `dict((['a',2], ['b', 3]), a=4, a=5)`. The resulting dictionary has len 2 (keys "a", "b") and len(kwargs) is also 2.

I suppose I could break updateDict into two halfs, positional and kwargs. Once positional args have been handled, then that optimization for kwargs works. Thoughts?

**Comment by josharian** [comment]
...or just do the work in updateDict. Duh.

**Comment by alandonovan** [comment]
> I don't think that that optimization is sound.

Oh, good point.

updateDict is the right place for the dynamic check, since we want it to apply to dict and dict.update, but I was hoping to get away from the need to make a second hashtable in the common case (success).  You could map each string to a value in [0-64] and set a bit and only do the slow check if there's a collision, but perhaps it's not worth the effort.

Also, if Python2 and Python3 both agree to statically forbid duplicate keyword args in a call, Starlark probably should too. I filed https://github.com/bazelbuild/starlark/issues/21.

**Comment by josharian** [comment]
I believe that #63 now contains a sound check for this. It is marked as fixing this issue, although given this issue and #54, it might still be worth manually checking whether all built-ins handle kwargs correctly, instead of waiting for go-fuzz to (maybe) find them.

**Comment by alandonovan** [comment]
Very few built-ins accept keyword arguments but don't use UnpackArgs, UnpackPositionalArgs, or explicity reject kwargs: I think it's just dict, dict.update, print. So the audit is done.
