### ISSUE TITLE
FR: implement io/fs or another filesystem interface 

### ISSUE THREAD

**Issue by discentem** [google/starlark-go#559]
I'm writing an application that embeds the starlark-go intepreter and implements some of my own domain-specific functions. I've started to write some integration tests (closed-box test against by go binary) and realized that starlark-go is writing/reading files directly with os.ReadFile (such [as here](https://github.com/google/starlark-go/blob/70002002b310c12a44e8389d18cfb34529b67ef4/internal/chunkedfile/chunkedfile.go#L59)). 

It would great if `starlark.ExecFile` and `starlark.ExecFileOptions` would accept an interface or struct for the filesystem, such as `io/fs` or something like afero. Is this a reasonable request? Do you have any alternative suggestions for doing this sort of closed-box testing? 

Thanks!

**Comment by discentem** [comment]
Hmm... I might be wrong about needing an fs interface to avoid touching the filesystem. Maybe if I don't pass filename and pass src, it'll work as I desire? 

https://github.com/google/starlark-go/blob/master/syntax/scan.go#L282

**Comment by adonovan** [comment]
> Maybe if I don't pass filename and pass src, it'll work as I desire?

Exactly. You can specify an arbitrary source for the apparent content of the filename.
