### ISSUE TITLE
Add support for "_" special variable in REPL mode to store last expression value

### ISSUE THREAD

**Issue by EastSPIRA** [google/starlark-go#569]
Similar to Python's REPL where "_" holds the value of the last expression, it would be valuable to have this functionality in Starlark's REPL mode.

Example of desired behavior:
```python
>>> 2 + 3
5
>>> _
5
>>> _ * 2
10
>>> _
10
```

Benefits:
- Improves interactive debugging and experimentation workflow
- Provides consistency with Python's REPL behavior, making it more intuitive for Python developers
- Useful for exploring computation results without explicitly assigning variables

Implementation considerations:
- Only needs to be active in REPL mode
- Should be updated after each complete expression evaluation
- Should not affect regular script execution outside REPL

The change would primarily affect the REPL implementation in cmd/starlark/main.go while maintaining Starlark's core principles of being a configuration language.

**Comment by adonovan** [comment]
I had never noticed that `_` worked that way in the Python REPL.

Sure, send me a PR.

**Comment by vt128** [comment]
@adonovan @EastSPIRA Please take a look at my PR #570

**Comment by adonovan** [comment]
Thanks!
