### ISSUE TITLE
strings have 'elems' attribute

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#69]
Mismatch vs python. I haven't dug yet to understand whether this is benign.

```
$ starlark -c "getattr('a', 'elems')"
15:28:40 ~/src/go.starlark.net/fuzz/corpus (fuzz)$ python2 -c "getattr('a', 'elems')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'str' object has no attribute 'elems'
15:28:42 ~/src/go.starlark.net/fuzz/corpus (fuzz)$ python3 -c "getattr('a', 'elems')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'str' object has no attribute 'elems'
```

Found by go-fuzz.

**Comment by alandonovan** [comment]
Working as intended. The elems method returns an iterator over string elements aka code units (UTF-8 here; UTF-16 in the Java impl). Python treats the string itself as iterable, a frequent source of bugs that result in Rob Pike receiving unwanted email as his userid is a single letter.
