### ISSUE TITLE
Issue tracker link in README is 404.

### ISSUE THREAD

**Issue by dmitshur** [google/starlark-go#7]
The README currently says:

> * Issue tracker: [https://go.starlark.net/starlark/issues](https://go.starlark.net/starlark/issues)

But that link is 404.

See:

https://github.com/google/starlark-go/blame/8474648b1aabb3712d0f2d2100a46c9974600188/README.md#L44

I'm not sure if the URL was changed from https://github.com/google/starlark/issues to https://go.starlark.net/starlark/issues unintentionally as part of a global replace in 6beab7ec164c8629c37f53b70d7b79dcbb9d44ef, or if that URL is meant to exist and redirect to GitHub. Hence an issue rather than PR.

**Comment by alandonovan** [comment]
Thanks for pointing it out. It was just an oversight. sed is a blunt instrument.
