### ISSUE TITLE
a math library

### ISSUE THREAD

**Issue by glycerine** [google/starlark-go#78]
Starlark seem mighty terrific. I just have a minor query about doing some math.

In starlark-go, how would one raise n to the m-th power?

In Go, I would call math.Pow(n, m). In Python, math.pow(n, m).

Another way of asking: is there a way to get at the math library from Go perhaps?

**Comment by glycerine** [comment]
addressed deeply by https://github.com/google/starlark-go/pull/79, where import of the standard libraries such as "math" is enabled.

**Comment by alandonovan** [comment]
We do need a way to do exponentiation. We could define the ** operator, but we would still need a math library similar to that of Python and/or Go, in which case ** is redundant, and though it may be convenient in Python, I suspect numeric work in Starlark will be relatively uncommon.

**Comment by b5** [comment]
@glycerine If there's any interest, we maintain a suite of library packages (including math) here: https://github.com/qri-io/starlib, I'd be happy to help make that work for your use case

**Comment by alandonovan** [comment]
Neat! The math and time packages in particular would be nice additions to go.starlark.net/lib, if that works for you.

**Comment by b5** [comment]
Absolutely! I'll try to put a PR together this weekend that includes your review comments. I'd love to see this code in go.starlark.net/lib 😄.

**Comment by fenollp** [comment]
Hello @b5 any progress on said PR?

I'm quite interested in your `math`, `time` and `re` modules as well :)

**Comment by essobedo** [comment]
@b5 Ready for this one 😄  ?

**Comment by b5** [comment]
lol if you are, I guess so! But first we should check if our PR will be accepted. @brandjon would you accept a math library PR from us, and if so who's the right person to tag for review?

**Comment by adonovan** [comment]
I'd be happy to review it, and I will try to be a little more responsive this time. ;-)

**Comment by b5** [comment]
sounds great! I'll open the PR to get the conversation going. IIRC @dustmop from our team wrote the initial library, and is a  much better pythonist than myself. @essobedo it'd be great to have you play a similar role this go-round if you're up for it 😄

**Comment by essobedo** [comment]
@b5 with pleasure, I'll do my best 😄 since I'm still learning Go (I'm rather a Java developer) and I like it

**Comment by brandjon** [comment]
Thanks for taking this review on Alan.
