### ISSUE TITLE
repl rejects multiline strings

### ISSUE THREAD

**Issue by glycerine** [google/starlark-go#81]
Sadly it is difficult to step through code line-by-line at the repl when the code contains multiline strings such as docstrings.
~~~
$ starlark
Welcome to Starlark (go.starlark.net)
>>> a = """trying to enter a multiline string at the repl 
... that has two newlines after this line...
...
<stdin>:1:5: unexpected EOF in string
>>> # arg.
~~~

**Comment by glycerine** [comment]
I fixed this on my fork. Let me know if you want a PR.

**Comment by alandonovan** [comment]
Thanks. Rather than add to the REPL's already excessive heuristics, I took a different approach of integrating the scanner/parsing and REPL, which fixes this and a bunch of related problems more cleanly.
