### ISSUE TITLE
inconsistent acceptance of trailing commas in argument lists

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#83]
```
$ starlark
Welcome to Starlark (go.starlark.net)
>>> def f(*args, **kwargs): pass
... 
>>> f(1,)
>>> f(*(1,2),)
... 
<stdin>:1:11: got ')', want argument
>>> f(a=1,)
>>> f(**{"a": 1},)
... 
<stdin>:1:15: got ')', want argument
>>>  
```

Observe that for plain positional and keyword args, a trailing comma is accepted. The other two cases are not.

Python 2 behaves the same as starlark-go; Python 3 accepts all forms.

I prefer the Python 3 behavior.

```
$ python2
Python 2.7.15 (default, Jun 17 2018, 12:46:58) 
>>> def f(*args, **kwargs): pass
... 
>>> f(1,)
>>> f(*(1,2),)
  File "<stdin>", line 1
    f(*(1,2),)
             ^
SyntaxError: invalid syntax
>>> f(a=1,)
>>> f(**{"a": 1},)
  File "<stdin>", line 1
    f(**{"a": 1},)
                ^
SyntaxError: invalid syntax
```

```
$ python3
Python 3.7.1 (default, Nov 14 2018, 12:09:13) 
>>> def f(*args, **kwargs): pass
... 
>>> f(1,)
>>> f(*(1,2),)
>>> f(a=1,)
>>> f(**{"a": 1},)
```

I haven't checked yet what the spec mandates.

**Comment by alandonovan** [comment]
I agree Python2 is inconsistent, but Starlark-Go and Starlark-Java are at least consistent with Python2, so that's good. The place to report this issue is at https://github.com/bazelbuild/starlark/. I'm happy to change the Go impl if all parties agree it's the right thing.

**Comment by josharian** [comment]
Thanks, Alan. Meant to do that but didn’t get to it. Closing this issue for now, at least until the other is resolved.
