### ISSUE TITLE
UnpackArgs: how to detect explicitly set parameters

### ISSUE THREAD

**Issue by fsenart** [google/starlark-go#92]
```python
# foo.star

fn(v = 0)
fn()
```

```go
// bar.go

var v int
starlark.UnpackArgs(r.Name(), args, kwargs, "v?", &v)
// How can we test if `v` has been explicitly set or has its default value?
```

Analogy with go `encoding/json` [strategy](https://golang.org/src/encoding/json/decode.go#L441):
```go
var v *int
json.Unmarshal([]byte(""), &v) 
// or
json.Unmarshal([]byte("0"), &v
// then
if v == nil {...}
```

**Comment by alandonovan** [comment]
> var v int
> starlark.UnpackArgs(r.Name(), args, kwargs, "v?", &v)
> // How can we test if `v` has been explicitly set or has its default value?

The simplest way is to choose an obscure default such as `var v int = -1`, but a user could explicitly pass -1 and you wouldn't be able to tell.

Another way is to declare v with type starlark.Value and do the type check yourself:
```
  var v starlark.Value
  UnpackArgs
  if v == nil { ... } //  no value supplied
  i, err := starlark.AsInt32(v)
  if err != nil { ... } // bad value supplied
```

**Comment by fsenart** [comment]
Thank you @alandonovan for your quick answer. The two proposed solutions are already the ones I use. By opening this issue, I also wanted to know if there is any chance for this kind of enhancement to be supported by default in the future? Performing a custom type check prevents me from taking advantage of work already done by starlark-go and obscure defaults cannot be a real solution as you've already noticed.

**Comment by alandonovan** [comment]
The Unpack*Args functions are helpers, nothing more. They handle a wide range of practical cases but certainly not all. They don't have any special access, so anything they do you can do yourself by copying a few lines of code.
