### ISSUE TITLE
Support break outside of function body

### ISSUE THREAD

**Issue by jazzdan** [google/starlark-go#97]
In [Tilt](https://github.com/windmilleng/tilt/) we are using Starlark as a general scripting language. The changes that were merged in f9eba728dc959ed06f508aaac74f1fe710800c8f have enabled our users to write a script, with logic, that exists at the top level.

I've encountered the desire for a `break` statement at the top level too, to turn "if else" that look like this:

```python
if param:
  build_one_way()
else:
  build_another_way()
```

In to this

```python
if param
  build_one_way()
  break

build_another_way()
```

I recognize that this [isn't allowed in Python](https://docs.python.org/3/reference/simple_stmts.html#the-return-statement), but I'm curious what your thoughts are on supporting this in pursuit of Starlark a general scripting language.

Thanks! Happy to help out with PRs if you think this is something you want to support.

**Comment by alandonovan** [comment]
I can't tell exactly what you are proposing, but I for one would be quite confused if I came across that construct knowing only Python or some C-like language. Where would control resume after the break statement?

I'm going to close this issue, but if you have a complete proposal for a language spec change, the place to send it is https://github.com/bazelbuild/starlark.

**Comment by jazzdan** [comment]
It wouldn't resume, execution would stop, but I see your point. `return` is nonsensical here.

What I see a need for is some way to stop execution programmatically outside of a function body. Upon further research it seems the way this is done in Python today is with `quit()` or `sys.exit()`.

It sounds like I should flesh out a `quit()` proposal and submit it to https://github.com/bazelbuild/starlark. Thanks!

**Comment by jazzdan** [comment]
Oh! I miswrote this issue. I meant for this to be a proposal to allow `return` statements outside of function bodies. Though that carries with it similar issues (what are you returning, to where?)

**Comment by alandonovan** [comment]
You can implement `quit` and `exit` without changing the core. The quit function would simply return an error, and the caller of ExecFile would have to recognize this error. The exit function would call os.Exit.
